from app.db.database import Base
from app.models.user import User
from app.models.doctor import Doctor
from app.models.slot import Slot
from app.models.working_hours import WorkingHours
from app.models.booking import Booking
from app.models.waitlist import Waitlist
from app.models.patient_profile import PatientProfile
from app.models.intake_brief import IntakeBrief
from app.models.patient_health_summary import PatientHealthSummary
from app.models.patient_medication import PatientMedication
from app.models.patient_document import PatientDocument
from app.models.document_template import DocumentTemplate