"""add lat lng to doctors

Revision ID: 3e1ab7f84591
Revises: 222597cf407a
Create Date: 2026-05-04 02:45:22.298925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e1ab7f84591'
down_revision: Union[str, Sequence[str], None] = '222597cf407a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('doctors', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'longitude')
    op.drop_column('doctors', 'latitude')
    # ### end Alembic commands ###
