"""add slot blocking, booking statuses, walk-in, documents

Revision ID: 5260b98416c2
Revises: bd2f5cb5146b
Create Date: 2026-05-01 14:07:26.653066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5260b98416c2'
down_revision: Union[str, Sequence[str], None] = 'bd2f5cb5146b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bookings', sa.Column('receptionist_note', sa.Text(), nullable=True))
    op.add_column('bookings', sa.Column('is_walk_in', sa.Boolean(), nullable=True))
    op.add_column('bookings', sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('slots', sa.Column('blocked_reason', sa.String(), nullable=True))
    op.add_column('slots', sa.Column('blocked_by', sa.UUID(), nullable=True))
    op.drop_column('slots', 'created_at')
    op.add_column('users', sa.Column('is_walk_in', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('claim_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('claimed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'claimed')
    op.drop_column('users', 'claim_code')
    op.drop_column('users', 'is_walk_in')
    op.add_column('slots', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('slots', 'blocked_by')
    op.drop_column('slots', 'blocked_reason')
    op.drop_column('bookings', 'completed_at')
    op.drop_column('bookings', 'arrived_at')
    op.drop_column('bookings', 'is_walk_in')
    op.drop_column('bookings', 'receptionist_note')
    op.drop_table('patient_documents')
    # ### end Alembic commands ###
