"""add intake_briefs outcome crisis_flag

Revision ID: 539d4dec32e7
Revises: 5a8dbec63ebb
Create Date: 2026-04-30 12:53:08.041642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '539d4dec32e7'
down_revision: Union[str, Sequence[str], None] = '5a8dbec63ebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intake_briefs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('main_concern', sa.Text(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('medications', sa.Text(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('language_used', sa.String(), nullable=True),
    sa.Column('crisis_flagged', sa.Boolean(), nullable=True),
    sa.Column('raw_brief', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.add_column('bookings', sa.Column('crisis_flag', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('outcome', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'outcome')
    op.drop_column('bookings', 'crisis_flag')
    op.drop_table('intake_briefs')
    # ### end Alembic commands ###
