"""add intake_briefs table and crisis_flag to bookings

Revision ID: 5a8dbec63ebb
Revises: c098ade53c7e
Create Date: 2026-04-30 12:27:24.067726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a8dbec63ebb'
down_revision: Union[str, Sequence[str], None] = 'c098ade53c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
