"""add patient health summaries and medications

Revision ID: cff71c4dd073
Revises: 83b4295fd736
Create Date: 2026-05-01 02:41:58.274170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cff71c4dd073'
down_revision: Union[str, Sequence[str], None] = '83b4295fd736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_health_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('total_visits', sa.String(), nullable=True),
    sa.Column('last_visit_date', sa.String(), nullable=True),
    sa.Column('specialties_seen', sa.Text(), nullable=True),
    sa.Column('medications_detected', sa.Text(), nullable=True),
    sa.Column('care_gaps_detected', sa.Text(), nullable=True),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('patient_medications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('medication_name', sa.String(), nullable=False),
    sa.Column('detected_from_intake', sa.Boolean(), nullable=True),
    sa.Column('last_prescribed_date', sa.String(), nullable=True),
    sa.Column('estimated_refill_date', sa.String(), nullable=True),
    sa.Column('refill_notified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_medications')
    op.drop_table('patient_health_summaries')
    # ### end Alembic commands ###
